name: Build Minecraft Java Edition with Gradle

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發
  pull_request:
    branches:
      - main  # 當對 main 分支提出拉取請求時觸發

jobs:
  build:
    runs-on: ubuntu-latest  # 選擇運行 Ubuntu 作為環境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 檢出代碼到工作環境

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'       # 指定 Java 版本
        distribution: 'temurin'  # 指定 Java 分發版本（例如 temurin）

    - name: Cache Gradle dependencies
      uses: actions/cache@v2  # 快取 Gradle 依賴，加速構建
      with:
        path: ~/.gradle/caches  # Gradle 快取目錄
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew  # 確保 gradlew 可執行

    - name: Build with Gradle
      run: ./gradlew build  # 使用 Gradle 進行構建

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: minecraft-build
        path: build/libs/*.jar  # 假設構建的 JAR 文件位於 build/libs 目錄下
